---MIGRATE---
CREATE EXTENSION IF NOT EXISTS pgcrypto;

---MIGRATE---
-- Demo login password for every row below: demo123.
-- Stored hash is bcrypt $2b generated by Python bcrypt, compatible with backend auth verify.
INSERT INTO users (email, full_name, role, password_hash)
VALUES
    (
        'admin.demo@sandy-lab.local',
        'Demo Admin',
        'admin',
        '$2b$12$bbIXQhy5o2w9ra8Y6pIW6Odd3oNxzkKSySAjUPSrnnhNsqflXrce2'
    ),
    (
        'researcher.demo@sandy-lab.local',
        'Demo Researcher',
        'researcher',
        '$2b$12$bbIXQhy5o2w9ra8Y6pIW6Odd3oNxzkKSySAjUPSrnnhNsqflXrce2'
    ),
    (
        'inventory.demo@sandy-lab.local',
        'Demo Inventory Clerk',
        'inventory',
        '$2b$12$bbIXQhy5o2w9ra8Y6pIW6Odd3oNxzkKSySAjUPSrnnhNsqflXrce2'
    ),
    (
        'viewer.demo@sandy-lab.local',
        'Demo Viewer',
        'viewer',
        '$2b$12$bbIXQhy5o2w9ra8Y6pIW6Odd3oNxzkKSySAjUPSrnnhNsqflXrce2'
    )
ON CONFLICT (email) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    password_hash = EXCLUDED.password_hash;
